---
abstract: 'String Length Comparisons'
author:
  - 'Michael Accardo <accardo@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: String-Compare-Length
requires:
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/mixedconnections/String-Compare-Length/issues
  homepage: https://github.com/mixedconnections/String-Compare-Length
  repository: https://github.com/mixedconnections/String-Compare-Length.git
version: '0.04'
